version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: ansible-lint
        versions:
          - 5.0.1
          - 5.0.5
      - dependency-name: docker
        versions:
          - 4.4.3
      - dependency-name: ansible
        versions:
          - 2.10.7
          - 2.9.2
