---
- name: Check for existing Docker Compose binary
  stat:
    path: "{{ docker_compose_path }}"
  register: check_docker_compose_binary
  changed_when: (False)

- name: Get output of "uname -s"
  command: uname -s
  register: uname_s
  changed_when: false
  when: (not check_docker_compose_binary.stat.exists)

- name: Get output of "uname -m"
  command: uname -m
  register: uname_m
  changed_when: false
  when: (not check_docker_compose_binary.stat.exists)

- name: Install docker compose
  get_url:
    url: "{{ docker_compose_url }}/{{ docker_compose_version }}\
      /docker-compose-{{ uname_s.stdout }}-{{ uname_m.stdout }}"
    dest: "{{ docker_compose_path }}"
    mode: "755"
  when: (not check_docker_compose_binary.stat.exists)
