---
- name: Install dependencies
  apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
      - ca-certificates
      # Required by the deb822_repository module.
      - python3-debian

- name: Create apt keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add Docker repository
  deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/debian
    suites: "{{ ansible_distribution_release }}"
    components: stable
    architectures: amd64
    signed_by: /etc/apt/keyrings/docker.asc
    state: present
    enabled: true

- name: Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: true

- name: Create /etc/docker
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Install daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: "0640"
  notify:
    - Restart docker
