---
- name: Login into Docker Registries
  docker_login:
    registry_url: "{{ item.registry_url }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
  loop: "{{ docker_engine_login }}"
  loop_control:
    label: "{{ item.registry_url }}"
