---
- name: Install dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - python-setuptools
      - python3-pip
      - python3-setuptools

- name: Install dependencies
  pip:
    name: "{{ packages }}"
  vars:
    packages:
      - docker

- name: Login into Docker Registries
  docker_login:
    registry_url: "{{ item.registry_url }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
  loop: "{{ docker_engine_login }}"
  loop_control:
    label: "{{ item.registry_url }}"
