---
- name: Install dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
    state: present

- name: Install Docker
  apt:
    name: docker-ce
    state: present
  notify:
    - run hello-world image

- name: Install daemon.json
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - restart docker

- name: Check for existing Docker Compose binary
  stat:
    path: "{{ docker_compose_path }}"
  register: check_docker_compose_binary
  changed_when: False

- name: Get output of "uname -s"
  shell: uname -s
  register: uname_s
  when: (not check_docker_compose_binary.stat.exists)

- name: Get output of "uname -m"
  shell: uname -m
  register: uname_m
  when: (not check_docker_compose_binary.stat.exists)

- name: Install docker compose
  get_url:
    url: "{{ docker_compose_url }}/{{ docker_compose_version }}/docker-compose-{{ uname_s.stdout }}-{{ uname_m.stdout }}"
    dest: "{{ docker_compose_path }}"
    mode: "755"
  when: (not check_docker_compose_binary.stat.exists)

- name: Setup docker-bench-security cronjob
  cron:
    name: "Run docker-bench-security."
    minute: "0"
    hour: "0"
    job: >
      docker run -it --net host --pid host --userns host --cap-add audit_control
      -e DOCKER_CONTENT_TRUST=$DOCKER_CONTENT_TRUST
      -v /etc:/etc:ro
      -v /usr/bin/containerd:/usr/bin/containerd:ro
      -v /usr/bin/runc:/usr/bin/runc:ro
      -v /usr/lib/systemd:/usr/lib/systemd:ro
      -v /var/lib:/var/lib:ro
      -v /var/run/docker.sock:/var/run/docker.sock:ro
      --label docker_bench_security
      docker/docker-bench-security
      -b
  when: docker_engine_bench_security_enabled
