---
- name: Install Docker Engine
  include_tasks: engine.yml

- name: Install Docker Compose
  include_tasks: compose.yml

- name: Include security related tasks
  include_tasks: security.yml

- name: Login into Docker Registries
  include_tasks: login.yml
