---
- name: Setup docker-bench-security cronjob
  cron:
    name: "Run docker-bench-security."
    minute: "0"
    hour: "0"
    job: >
      docker run --net host --pid host --userns host --cap-add audit_control
      -e DOCKER_CONTENT_TRUST=$DOCKER_CONTENT_TRUST
      -v /etc:/etc:ro
      -v /usr/bin/containerd:/usr/bin/containerd:ro
      -v /usr/bin/runc:/usr/bin/runc:ro
      -v /usr/lib/systemd:/usr/lib/systemd:ro
      -v /var/lib:/var/lib:ro
      -v /var/run/docker.sock:/var/run/docker.sock:ro
      --label docker_bench_security
      docker/docker-bench-security
      -b
  when: docker_engine_bench_security_enabled

- name: Install auditd
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - auditd
  when: docker_engine_auditd

- name: Install auditd rules
  blockinfile:
    path: /etc/audit/rules.d/audit.rules
    marker: "# {mark} DOCKER ANSIBLE MANAGED BLOCK"
    block: |
      -w /usr/bin/docker -p wa
      -w /var/lib/docker -p wa
      -w /etc/docker -p wa
      -w /lib/systemd/system/docker.service -p wa
      -w /lib/systemd/system/docker.socket -p wa
      -w /etc/default/docker -p wa
      -w /etc/docker/daemon.json -p wa
      -w /usr/bin/docker-containerd -p wa
      -w /usr/bin/docker-runc -p wa
    state: present
  notify:
    - restart auditd
  when: docker_engine_auditd

- name: Enabled Content Trust
  lineinfile:
    path: /etc/environment
    regexp: "^DOCKER_CONTENT_TRUST="
    line: DOCKER_CONTENT_TRUST=1
    state: present
  when: docker_engine_content_trust

- name: Disable Content Trust
  lineinfile:
    path: /etc/environment
    regexp: "^DOCKER_CONTENT_TRUST="
    state: absent
  when: not docker_engine_content_trust
